[package]
name = "kakebo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
crossterm = "0.27.0"
nom = "7.1.3"
ratatui = "0.26.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.56"
toml = "0.8.10"
